plugins {
    id 'application'
    id 'org.springframework.boot' version '3.2.0'
    id 'io.spring.dependency-management' version '1.1.6'
}

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.spring.io/milestone'
    }
    maven {
        url = 'https://repo.spring.io/snapshot'
    }
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.ai:spring-ai-bom:1.0.0-M4'
    }
}

dependencies {
    implementation 'org.postgresql:postgresql:42.7.2'


    implementation 'org.jetbrains:annotations:24.1.0'


    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'

    testCompileOnly 'org.projectlombok:lombok:1.18.36'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.36'


    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.1'


    implementation 'org.springframework.ai:spring-ai-transformers-spring-boot-starter'
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.ai:spring-ai-pgvector-store'

    implementation 'com.google.genai:google-genai:1.0.0'

    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'


    implementation 'io.github.cdimascio:dotenv-java:3.0.0'
}

test {
    useJUnitPlatform()
}

application {
    mainClass = 'wordwizard.App'
}

run {
    environment = System.getenv()
}